#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root."
    exit 1
fi

while getopts ":t:" opt; do
    case $opt in
        t)
            record_type="$OPTARG"
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG."
            exit 1
            ;;
    esac
done

if [ -z "$record_type" ]; then
    record_type="A"
fi

case $record_type in
    A)
	shift $((OPTIND - 1))
	hostname="$1"
	ip_address="$2"
	zone="$3"
        echo -e "$hostname\tIN\tA\t$ip_address" >> "/etc/bind/mrt-zone-files/db.$zone"
        ;;
    MX)
	shift $((OPTIND - 1))
	hostname="$1"
	ip_address="$2"
	zone="$3"    
        echo -e "@\tIN\tMX\t10\t$hostname.tim-vanderperre.sb.uclllabs.be." >> "/etc/bind/mrt-zone-files/db.$zone"
        echo -e "$hostname\tIN\tA\t$ip_address" >> "/etc/bind/mrt-zone-files/db.$zone"
        ;;
    CNAME)
	
	shift $((OPTIND - 1))
	hostname="$1"
	zone="$2"
        echo -e "$hostname.tim-vanderperre.sb.uclllabs.be.\tIN\tCNAME\t$zone" >> "/etc/bind/mrt-zone-files/db.$zone"
        ;;
    *)
        echo "Error: Invalid record type."
        exit 1
        ;;
esac

# Increase serial number
old=$(grep "Serial" "/etc/bind/mrt-zone-files/db.$zone" | tr -dc '0-9')
new=$((old + 1))
sed -i "s/$old\t\t;\sSerial/$new\t\t; Serial/" "/etc/bind/mrt-zone-files/db.$zone"

# Reload the DNS server
rndc reload
systemctl restart bind9

