#!/bin/bash

# Check if the script is being run by root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

# Check if the FQDN argument is provided
if [[ -z $1 ]]; then
    echo "Please provide the FQDN as an argument."
    exit 1
fi

# Extract the subdomain and zone from the FQDN
fqdn=$1
subdomain=${fqdn%%.*}
zone=${fqdn#*.}

# Check if the zone has the IP address 193.191.177.226
ip_address=$(dig +short $fqdn @1.1.1.1)
if [[ $ip_address != "193.191.177.226" ]]; then
    echo "'$fqdn' is not a zone or  does not have the required IP address."
    exit 1
fi

# Create the DocumentRoot directory
    mkdir -p "/var/www/$subdomain"
   # echo "welcome $fqdn" >> "/var/www/$subdomain/index.html"
    echo "welcome $fqdn" >> "/var/www/$subdomain/index.html"



# Create the vhost configuration file
vhost_conf="/etc/apache2/sites-available/$fqdn.conf"
cat <<EOF >"$vhost_conf"
<VirtualHost *:80>
    ServerName $fqdn
    ServerAlias $fqdn
    DocumentRoot /var/www/$subdomain
    ErrorLog \${APACHE_LOG_DIR}/$fqdn.error.log
    CustomLog \${APACHE_LOG_DIR}/$fqdn.access.log combined
</VirtualHost>
EOF

# Enable the vhost
a2ensite "$fqdn.conf"

# Restart Apache
echo "restarting apache2 automatically because of the script."
systemctl restart apache2

